export const MOCK_DATA = [
  {
    id: "e-1001",
    nombre: "Cafetería La Mesa",
    fechaAlta: "2025-07-15",
    admin: "María Rivas",
    telefono: "+34 600123123",
    email: "contacto@lamesa.es",
    direccion: "C/ Gran Vía 123, Madrid",
    plan: "Basico",
    locales: [
      { id: "l-1", nombre: "Gran Vía" },
      { id: "l-2", nombre: "Chueca" },
    ],
  },
  {
    id: "e-1002",
    nombre: "Clínica Sonrisa Total",
    fechaAlta: "2025-08-01",
    admin: "J. Paredes",
    telefono: "+34 611222333",
    email: "info@sonrisatotal.es",
    direccion: "Av. América 45, Madrid",
    plan: "Plus",
    locales: [{ id: "l-3", nombre: "Sede Central" }],
  },
  {
    id: "e-1003",
    nombre: "Moda Bohema",
    fechaAlta: "2025-06-10",
    admin: "R. Fernández",
    telefono: "+34 622333444",
    email: "hola@modabohema.es",
    direccion: "Calle Fuencarral 9, Madrid",
    plan: "Empresarial",
    locales: [],
  },
  {
    id: "e-1004",
    nombre: "Hatillo Arepas",
    fechaAlta: "2025-04-22",
    admin: "A. Giménez",
    telefono: "+34 633444555",
    email: "hola@hatillo.es",
    direccion: "C/ Alcalá 200, Madrid",
    plan: "Empresarial",
    locales: [{ id: "l-9", nombre: "Alcalá" }],
  },
];
